version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
    container_name: app
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "dockerize -wait tcp://db:3306 -timeout 20s && exec docker-entrypoint.sh npm start",
      ]
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peopledb
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  mysql:
